default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("RAILS_DB_HOST") { "db" } %>
  username: <%= ENV.fetch("RAILS_DB_USERNAME") { "root" } %>
  password: <%= ENV.fetch("MYSQL_ROOT_PASSWORD") { "password" } %>
  host: <%= ENV.fetch("RAILS_DB_HOST") { "db" } %>

development:
  <<: *default
  database: app_name_development

test:
  <<: *default
  database: app_name_test


production:
  <<: *default
  database: app_name_production
  username: app_name
  password: <%= ENV['APP_NAME_DATABASE_PASSWORD'] %>
